version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mariadb:10.7
    env_file:
      - ./app/.env
    ports:
      - 3306:3306
    volumes:
      - my_db:/var/lib/mysql

volumes:
  my_db:
